services:
  bot:
    build: ./bot
    environment:
      TELEGRAM_TOKEN:
      CERT_SHA_KEY:
      ACCOUNT_ID: 
      SECRET_KEY: 
      DB_USERNAME:
      DB_PASS:
      DB_HOST:
      DB_PORT:
      DB_NAME:
      API_URL: 
      USERNAME_API:
      # PASSWORD_API:
      PASSWORD_API:
    restart: unless-stopped
    depends_on:
      - postgres

  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USERNAME=
      - POSTGRES_PASSWORD=
      - POSTGRES_NAME=
    volumes:
      - ./psql-data/:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    volumes:
      - redis_data:/data

volumes:
  redis_data:
